version: '3.9'

services:
  archivo:
    image: archivo-api
    container_name: archivo-container 
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - archivo-network
    depends_on:
      - mysql

  mysql:
    image: mysql
    container_name: mysql-database
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: archivo
      MYSQL_USER: archivo_user
      MYSQL_PASSWORD: 123456
    ports:
      - "3307:3306"
    networks:
    - archivo-network
    volumes:
    - mysql-volume:/var/lib/mysql

networks:
  archivo-network:

volumes:
  mysql-volume: